@textprocessor_dropzone_HostAddress = http://localhost:5054


POST {{textprocessor_dropzone_HostAddress}}/api/textprocessor/singularize/
Content-Type: application/json

{
    "content": "Test Values"
}

