on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies in Subdirectory
      run: npm ci
      working-directory: ./nivo-storybook-charting
        
    - id: build-publish
      uses: bitovi/github-actions-react-to-github-pages@v1.2.4
      with:
        path: storybook-static # change to your build folder
